version: "3"
services:
    app:
        image: app:latest
        ports: 
            - 5000:5000
        volumes: 
            - ./src:/app
    db:
        image: postgres:13.3-alpine
        environment: 
            POSTGRES_PASSWORD: "foobar"
        volumes:
            - ../data:/var/lib/postgresql/data
