apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-db-st
spec:
  serviceName: app-db-svc
  selector:
    matchLabels:
      app: app-db-statefulset
  template:
    metadata:
      name: app-db-pod
      labels:
        app: app-db-statefulset
    spec:
      containers:
      - name: postgres-container
        image: postgres:13.3-alpine
        env:
          - name: POSTGRES_PASSWORD
            value: "foobar"
        ports:
          - containerPort: 5432
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: app-pvc